version: '3.7'

services:
  nginx:
    image: nginx:1.12.1-alpine
    ports:
      - "8082:80"
      - "8080:8080"
    volumes:
      - ./docker/logs/nginx:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./services:/var/www/vhosts
    depends_on:
      - app

  app:
    build: docker/app
    ports:
      - "9000:9000"
    volumes:
      - ./services:/var/www/vhosts
      - ./bin/composer:/usr/local/bin/composer
      - ./bin/migrations:/usr/local/bin/migrations
    environment:
      - ENV=development
      - API_KEY=C6E84D247E2D81B5B45D6D2D229D9
    depends_on:
      - rabbit

  signup-service:
    build: docker/service
    restart: always
    volumes:
      - ./services/signup:/var/www/vhosts/app
    environment:
      - ENV=development
    depends_on:
      - rabbit
      - signup-db

  mailer-service:
    build: docker/service
    restart: always
    volumes:
      - ./services/mailer:/var/www/vhosts/app
    environment:
      - ENV=development
    depends_on:
      - rabbit

  signup-db:
    image: postgres:10.2-alpine
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - signup-data:/var/lib/postgresql/data
      - ./docker/postgresql/signup:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: 'ns-signups'
      POSTGRES_PASSWORD: password
      POSTGRES_DB: 'ns-signups'

  rabbit:
    image: rabbitmq:3-management
    ports:
      - "8081:15672"

  mail:
    ports:
      - "1025:25"
      - "1080:80"
    image: tophfr/mailcatcher

volumes:
    signup-data: {}